blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

cv/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

cw/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('', RedirectView.as_view(url='blog')),
    re_path(r'^blog/?', include(('blog.urls', 'blog'), namespace='blog')),
    re_path(r'^cv/?', include(('cv.urls', 'cv'), namespace='cv')),
    re_path(r'^unt/?', TemplateView.as_view(template_name="unt.html"), name="unt"),
    re_path(r'^admin/?', admin.site.urls),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

MAX = 14


class Post(models.Model):
    title = models.CharField(max_length=255, blank=True, default="", verbose_name='')
    content = models.TextField(blank=True, default="", verbose_name='')
    author = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    pin = models.BooleanField(default=False)

    def __str__(self):
        name = self.title if self.title else self.content
        return name[:MAX].strip() + ('...' if len(name) > MAX else '')

cv/models.py
from django.db import models

MAX = 14


class Details(models.Model):
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    email = models.EmailField()


class Link(models.Model):
    text = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return self.text


class School(models.Model):
    name = models.CharField(max_length=255)
    time = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    grade = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Work(models.Model):
    name = models.CharField(max_length=255)
    time = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    experience = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Achievement(models.Model):
    time = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.description[:MAX].strip() + ('...' if len(self.description) > MAX else '')

blog/views.py
from django.shortcuts import render
from .models import Post


def index(request):
    return render(request, 'blog/index.html',
        {'posts': Post.objects.order_by('-pin', '-date')})

cv/views.py
from django.shortcuts import render

from .models import *


def index(request):
    return render(request, 'cv/index.html',
        {'details': Details.objects.first(),
         'links': Link.objects.all(),
         'education': School.objects.all(),
         'career': Work.objects.all(),
         'achievements': Achievement.objects.all()
        })

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  {% for post in posts %}
    <div class="post">
      <h3>{{ post.title }}</h3>
      <pre>{{ post.content }}</pre>
      <small>
        <abbr title="Posted by {{ post.author }}">
          {{ post.date | date:"d/m/y, H:i" }}
        </abbr>
        {% if post.pin %}
          <abbr title="pinned">📌</abbr>
        {% endif %}
      </small>
    </div>
  {% endfor %}
{% endblock %}

cv/templates/cv/index.html
{% extends 'base.html' %}

{% block content %}
<div class="cv">
  <div>
    <h3>{{ details.name }}</h3>
    <h3>{{ details.number }}</h3>
    <h3>{{ details.address }}</h3>
    <h3>{{ details.email }}</h3>
  </div>
  {% for link in links %}
    <h3><a href="{{ link.url }}">{{ link.text }}</a></h3>
  {% endfor %}
  <h2>Education</h2>
  {% for school in education %}
  <div>
    <p>
      <b>{{ school.name }}</b> ({{ school.time }})
    </p>
    <p>{{ school.subject }}: {{ school.grade }}</p>
  </div>
  {% endfor %}
  <h2>Career</h2>
  {% for work in career %}
  <div>
    <p>
      <b>{{ work.name }}</b> ({{ work.time }})
    </p>
    <p><i>{{ work.position }}</i></p>
    <p>{{ work.description }}</p>
    <p>{{ work.experience }}</p>
  </div>
  {% endfor %}
  <h2>Projects and achievements</h2>
  <ul>
  {% for achievement in achievements %}
     <li>{{ achievement.description }} ({{ achievement.time }})</li>
  {% endfor %}
  </ul>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet", type="text/css", href="{% static 'style.css' %}">
    <link rel="icon" type="image/png" href="{% get_static_prefix %}favicon/{{ mon }}.ico">
    <title>amitai.ga</title>
  </head>
  <body>
    <div class="nav">
      <h1>
        amitai.ga<a href="{% url 'unt' %}" class="unt">unt</a>
      </h1>
      <a href="{% url 'blog:index' %}">blog</a>
      | <a href="{% url 'cv:index' %}">cv</a>
      | <a href="https://github.com/amg-12/cw">source</a>
      | <a href="{% url 'admin:index' %}">admin</a>
    </div>

    {% block content %}{% endblock %}

  </body>
</html>

templates/unt.html
{% extends 'base.html' %}

{% block content %}
  <p>yep, that's me</p>
{% endblock %}